name: disiplean_clone
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_storage: ^11.2.8
  google_fonts: ^6.1.0
  page_transition: ^2.1.0
  firebase_database: ^10.2.7
  uuid: ^4.1.0
  provider: ^6.0.5
  dart_date: ^1.2.2
  intl: ^0.18.1
  flutter_iconpicker: ^3.2.4
  flutter_easyloading: ^3.0.5
  flutter_downloader: ^1.11.5
  file_picker: ^6.1.1
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1
  image_picker: ^0.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
